jobs:
  include:
  - stage: Stage1
    name: "STAGE1"
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - if [ $TRAVIS_BRANCH == "develop" ] || [[ $TRAVIS_BRANCH == "master" ]];
      then
        echo "Generating release notes for publishing to Confluence";
        if [ $TRAVIS_BRANCH == "master" ];
        then
          ./scripts/devops/set_automation_build_flag.py master;
        else
          ./scripts/devops/set_automation_build_flag.py develop;
        fi;
      fi
