jobs:
  include:
  - stage: Android
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    before_install:
    - echo "Android Before Install 1"
    install:
    - echo "Android Install 1"
    - echo $TRAVIS_BUILD_NUMBER
    script:
    - echo "1"
    - echo "2"
    - echo "Commits in this release are as below"
    - echo $TRAVIS_COMMIT_RANGE
  - stage: Android
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    before_install:
    - echo "Android Before Install 2"
    install:
    - echo "Android Install 2"
    - echo $TRAVIS_BUILD_NUMBER
    script:
    - echo "1"
    - echo "2"
    - echo "Commits in this release are as below"
    - echo $TRAVIS_COMMIT_RANGE
  - stage: Node
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    before_install:
    - echo "Node Before Install"
    install:
    - echo "Node Install"
    - echo $TRAVIS_BUILD_NUMBER
    script:
    - echo "Commits in this release are as below"
    - echo $TRAVIS_COMMIT_RANGE