jobs:
  include:
  - stage: Android
    name: "JOB1"
    if: branch =~ /^release/[vV][0-9]+\.[0-9]+)$/
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - echo $MYBRANCH