branches:
  except:
  - v2.999
  - v1.95
  only:
  - develop
  - master
  - /^epic/.*$/
  - /^fix/CNTBG-[0-9]+/.*$/
  - /^feature/CNTBG-[0-9]+/.*$/
  - /^release-v[0-9]+\.[0-9]+(\.[0-9]+)?$/
  - /^v[0-9]+\.[0-9]+(\.[0-9]+)?$/
jobs:
  include:
  - stage: Stage1
    name: "STAGE1"
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - export RUN_AUTOMATION=true
  - stage: Stage2
    name: "STAGE2"
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - echo $RUN_AUTOMATION
