branches:
  only:
  - master
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
install:
- yarn --version
jobs:
  include:
  - stage: Unit Tests
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    before_install:
    - echo "Before Running TEST"
    install:
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    script:
    - echo "Running TEST"
  - stage: build
    language: android
    os: linux
    jdk: oraclejdk8
    sudo: required
    before_install:
    - echo "Before Running ANDROID"
    install:
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    script:
    - echo "Running ANDROID"
  - stage: build
    name: "iOS Release Build"
    language: objective-c
    os: osx
    osx_image: xcode9
    sudo: required
    before_install:
    - echo "Before Running IOS"
    install:
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    script:
    - echo "Running IOS"
  - stage: build
    name: "iOS Automation Build"
    language: objective-c
    os: osx
    osx_image: xcode9
    sudo: required
    before_install:
    - echo "Before Running IOS"
    install:
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    script:
    - echo "Running IOS"