jobs:
  include:
  - stage: Android
    name: "JOB1"
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - echo $MYBRANCH
  - stage: Android
    name: "JOB2"
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - echo $MYBRANCH

