jobs:
  include:
  - stage: Stage1
    name: "STAGE1"
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - hostname
    - ifconfig -a
    - curl http://canhazip.com
