jobs:
  include:
  - stage: Android
    name: "JOB1"
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - echo "THIS IS A BRANCH BUILD"
  - stage: Android
    name: "JOB2"
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - git --no-pager log origin/MYTESTTAG..  --format="%h,%an,%cn,%cd,%s" --date=short --first-parent origin/master

