branches:
  only:
  - develop
  - master
  - /^release/[vV][0-9]+\.[0-9]+$/
  - /^fix/CNTBG-[0-9]+/.*$/
  - /^feature/CNTBG-[0-9]+/.*$/
  - /^[vV][0-9]+\.[0-9]+(-trial)?$/

jobs:
  include:
  - stage: Android
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - if [ $TRAVIS_BRANCH == "develop" ] || [ $TRAVIS_BRANCH == "master" ] || [[ $TRAVIS_BRANCH =~ $RC_BRANCH_PATTERN ]];
      then
        echo "Matched $TRAVIS_BRANCH";
      else
        echo "Not Match $TRAVIS_BRANCH";
      fi