jobs:
  include:
  - stage: Android
    if: branch = develop OR 
        branch = '"develop"' OR 
        branch = master OR
        branch =~ /^(feature|fix)/CNTBG-[0-9]+/.*$/ #OR 
        #branch =~ /^fix/CNTBG-[0-9]+/.*$/
        #tag =~ /^[vV][0-9]+\.[0-9]+(-trial)?$/
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - echo "Changes in this Build - $TRAVIS_BUILD_NUMBER"
    - export CHANGELOG=`git --no-pager log $TRAVIS_COMMIT_RANGE --pretty=format:"%h - %s%n"`
    - echo $CHANGELOG
  - stage: Android
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - if [ $TRAVIS_BRANCH == "develop" ] || [ $TRAVIS_BRANCH == "master" ] || [[ $TRAVIS_BRANCH =~ $RC_BRANCH_PATTERN ]];
      then
        echo "1";
      else
        echo "2";
      fi