jobs:
  include:
  - stage: Android
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    install:
    - echo "Android Install 1"
    - echo $TRAVIS_BUILD_NUMBER
    script:
    - echo "Android Script 1"
  - stage: Android
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    install:
    - echo "Android Install 2"
    - echo $TRAVIS_BUILD_NUMBER
    script:
    - echo "Android Before Script 2"
  - stage: Node
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    before_install:
    - echo "Node Before Install"
    install:
    - echo "Node Install"
    - echo $TRAVIS_BUILD_NUMBER
    script:
    - echo "Changes in this Build - $TRAVIS_BUILD_NUMBER"
    - git --no-pager log $TRAVIS_COMMIT_RANGE --format="%h - %s"