jobs:
  include:
  - stage: Android
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    install:
    - echo "Android Install 1"
    - echo $TRAVIS_BUILD_NUMBER
    script:
    - echo "Changes in this Build - $TRAVIS_BUILD_NUMBER"
    - export CHANGELOG=`git --no-pager log $TRAVIS_COMMIT_RANGE --format="%h - %s\n"`
    - echo $CHANGELOG
  - stage: Android
    language: node_js
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    install:
    - echo "Android Install 2"
    - echo $TRAVIS_BUILD_NUMBER
    script:
    - echo "Changes in this Build - $TRAVIS_BUILD_NUMBER"
    - export CHANGELOG=`git --no-pager log $TRAVIS_COMMIT_RANGE --pretty=format:"%h - %s\\n"`
    - echo $CHANGELOG