jobs:
  include:
  - stage: Android
    name: "JOB1"
    node_js:
    - "8"
    os: linux
    jdk: oraclejdk8
    sudo: required
    script:
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_COMMIT_RANGE


