trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    exclude:
    - '*'

jobs:
- job: Testjob
  #condition: or(contains(variables['SCENARIOS'], 'E2E '), contains(variables['SCENARIOS'], ' E2E'), eq(variables['SCENARIOS'], 'E2E'), eq(variables['SCENARIOS'], ''))
  condition: containsValue(variables['SCENARIOS'], '"E2E"')
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'



#or(eq(variables['SCENARIOS'], 'E2E'), eq(variables['SCENARIOS'], ''))

#contains(variables['SCENARIOS'], ' ASV '), contains(variables['SCENARIOS'], 'ASV ')