trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Test job
  condition: containsValue(variables['SCENARIOS'], 'E2E ')
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'