trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Test job
  condition: or(contains(variables['SCENARIOS'], 'E2E '), contains(variables['SCENARIOS'], ' E2E'), eq(variables['SCENARIOS'], 'E2E'), eq(variables['SCENARIOS'], ''))
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'